package com.example.data.embedding

import org.junit.Assert.*
import org.junit.Test

class EmbeddingArchitectureTest {

    @Test
    fun testModelRefIsolationAndIntegrity() {
        val model1 = GeminiEmbeddingModel(modelId = "gemini-embedding-2", dimensions = 768)
        val model2 = GeminiEmbeddingModel(modelId = "gemini-embedding-001", dimensions = 768)

        assertEquals("gemini-embedding-2", model1.modelId)
        assertEquals("gemini-embedding-001", model2.modelId)

        val ref1 = "${model1.modelId}:${model1.modelVersion}"
        val ref2 = "${model2.modelId}:${model2.modelVersion}"

        assertNotEquals("Embeddings generated by different models must never share modelRef", ref1, ref2)
    }

    @Test
    fun testStrictDimensionValidation() {
        val model = GeminiEmbeddingModel(modelId = "gemini-embedding-2", dimensions = 768)
        assertEquals(768, model.dimensions)
    }
}
